version: '3'

services:
  imagechat_chat:
    image: imagechat_chat
    restart: always
    networks:
      - server
    logging:
      options:
        max-size: "100k"
        max-file: "3"
    labels:
      - traefik.enable=true
      - traefik.docker.network=server

      - traefik.http.services.imagechat_chat_rest.loadbalancer.server.port=8101
      - traefik.http.routers.imagechat_chat_rest.service=imagechat_chat_rest
      - traefik.http.routers.imagechat_chat_rest.rule=Host(`imagechat.getitqec.com`) && PathPrefix(`/api/chat/`)
      - traefik.http.routers.imagechat_chat_rest.entrypoints=https
      - traefik.http.routers.imagechat_chat_rest.tls.certresolver=mytlschallenge

      - traefik.http.services.imagechat_chat_grpc.loadbalancer.server.port=8100
      - traefik.http.services.imagechat_chat_grpc.loadbalancer.server.scheme=https
      - traefik.http.routers.imagechat_chat_grpc.service=imagechat_chat_grpc
      - traefik.http.routers.imagechat_chat_grpc.rule=Host(`imagechat.getitqec.com`) && PathPrefix(`/serviceproto.ChatService/`)
      - traefik.http.routers.imagechat_chat_grpc.entrypoints=grpc
      - traefik.http.routers.imagechat_chat_grpc.tls.certresolver=mytlschallenge
    container_name: imagechat_chat

networks:
  server:
    external: true
