version: '3'

services:
  imagechat_mailnotification:
    image: imagechat_notification
    restart: always
    networks:
      - server
    logging:
      options:
        max-size: "100k"
        max-file: "3"
    # ports: 
    #   - 8091:8091
    # command: [ "./cmd/server" ]
    labels:
      - traefik.enable=true
      - traefik.docker.network=server

      - traefik.http.services.imagechat_mailnotification_rest.loadbalancer.server.port=8121
      - traefik.http.routers.imagechat_mailnotification_rest.service=imagechat_mailnotification_rest
      - traefik.http.routers.imagechat_mailnotification_rest.rule=Host(`imagechat.getitqec.com`) && PathPrefix(`/api/notification/`)
      - traefik.http.routers.imagechat_mailnotification_rest.entrypoints=https
      - traefik.http.routers.imagechat_mailnotification_rest.tls.certresolver=mytlschallenge

      - traefik.http.services.imagechat_mailnotification_grpc.loadbalancer.server.port=8120
      - traefik.http.services.imagechat_mailnotification_grpc.loadbalancer.server.scheme=https
      - traefik.http.routers.imagechat_mailnotification_grpc.service=imagechat_mailnotification_grpc
      - traefik.http.routers.imagechat_mailnotification_grpc.rule=Host(`imagechat.getitqec.com`) && PathPrefix(`/serviceproto.MailNotificationService/`)
      - traefik.http.routers.imagechat_mailnotification_grpc.entrypoints=grpc
      - traefik.http.routers.imagechat_mailnotification_grpc.tls.certresolver=mytlschallenge
    container_name: imagechat_notification

networks:
  server:
    external: true
